/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.panels.prestamos;
import view.panels.librosDispo;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author YOJHAN DAVID
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public dashboard() {
        initComponents();
        
        librosDispo libDispo = new librosDispo();
        libDispo.setSize(717, 616);
        libDispo.setLocation(0,0);
        
        content.removeAll();
        content.add(libDispo, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titulo = new javax.swing.JLabel();
        bgTitulo = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        logo4 = new javax.swing.JLabel();
        logo3 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        librosDispoBtt = new javax.swing.JButton();
        prestamosBtt = new javax.swing.JButton();
        reportesBtt = new javax.swing.JButton();
        historialPrestamosBtt = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 130, 740, 620));

        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("2025 TM.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        titulo.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        titulo.setText("BookFlow");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        bgTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bgTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banner.jpg"))); // NOI18N
        jPanel1.add(bgTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 740, 130));

        menu.setBackground(new java.awt.Color(51, 153, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informe-seo.png"))); // NOI18N
        logo4.setToolTipText("");
        menu.add(logo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 40, 60));

        logo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expediente.png"))); // NOI18N
        menu.add(logo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, 60));

        logo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prestamo.png"))); // NOI18N
        menu.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 40));

        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libro-abierto.png"))); // NOI18N
        logo1.setToolTipText("");
        menu.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 40));

        librosDispoBtt.setBackground(new java.awt.Color(204, 204, 204));
        librosDispoBtt.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        librosDispoBtt.setText("Libros Disponibles");
        librosDispoBtt.setBorder(null);
        librosDispoBtt.setBorderPainted(false);
        librosDispoBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosDispoBttActionPerformed(evt);
            }
        });
        menu.add(librosDispoBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 60));

        prestamosBtt.setBackground(new java.awt.Color(204, 204, 204));
        prestamosBtt.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        prestamosBtt.setText("Prestamos");
        prestamosBtt.setBorder(null);
        prestamosBtt.setBorderPainted(false);
        prestamosBtt.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        prestamosBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamosBttActionPerformed(evt);
            }
        });
        menu.add(prestamosBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 60));

        reportesBtt.setBackground(new java.awt.Color(204, 204, 204));
        reportesBtt.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        reportesBtt.setText("Reportes");
        reportesBtt.setBorder(null);
        reportesBtt.setBorderPainted(false);
        reportesBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesBttActionPerformed(evt);
            }
        });
        menu.add(reportesBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 240, 60));

        historialPrestamosBtt.setBackground(new java.awt.Color(204, 204, 204));
        historialPrestamosBtt.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        historialPrestamosBtt.setText("Historial Prestamos");
        historialPrestamosBtt.setBorder(null);
        historialPrestamosBtt.setBorderPainted(false);
        historialPrestamosBtt.setMaximumSize(new java.awt.Dimension(76, 22));
        historialPrestamosBtt.setMinimumSize(new java.awt.Dimension(76, 22));
        historialPrestamosBtt.setPreferredSize(new java.awt.Dimension(76, 22));
        historialPrestamosBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialPrestamosBttActionPerformed(evt);
            }
        });
        menu.add(historialPrestamosBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 60));

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void librosDispoBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosDispoBttActionPerformed
        // TODO add your handling code here:
        
        librosDispo libDispo = new librosDispo();
        libDispo.setSize(717, 616);
        libDispo.setLocation(0,0);
        
        content.removeAll();
        content.add(libDispo, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_librosDispoBttActionPerformed

    private void reportesBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesBttActionPerformed
        // TODO add your handling code here:
        
        prestamos prest = new prestamos();
        prest.setSize(717, 616);
        prest.setLocation(0,0);
        
        content.removeAll();
        content.add(prest, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_reportesBttActionPerformed

    private void prestamosBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamosBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prestamosBttActionPerformed

    private void historialPrestamosBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialPrestamosBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historialPrestamosBttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgTitulo;
    private javax.swing.JPanel content;
    private javax.swing.JButton historialPrestamosBtt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton librosDispoBtt;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel logo3;
    private javax.swing.JLabel logo4;
    private javax.swing.JPanel menu;
    private javax.swing.JButton prestamosBtt;
    private javax.swing.JButton reportesBtt;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
