/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author YOJHAN DAVID
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        tituloLogin = new javax.swing.JLabel();
        fondoLogin = new javax.swing.JLabel();
        iniciarSes = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        iniciarSes1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldContraseña = new javax.swing.JPasswordField();
        accederBtt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libro-abierto.png"))); // NOI18N
        LOGO.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        background.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 40, 110));

        usuarioLabel.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        usuarioLabel.setText("Usuario");
        background.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 460, 50));

        tituloLogin.setFont(new java.awt.Font("JetBrains Mono", 1, 48)); // NOI18N
        tituloLogin.setForeground(new java.awt.Color(242, 242, 242));
        tituloLogin.setText("BookFlow");
        background.add(tituloLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 240, 50));

        fondoLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreriaBg.jpg"))); // NOI18N
        fondoLogin.setText("jLabel1");
        background.add(fondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 340, 750));

        iniciarSes.setFont(new java.awt.Font("JetBrains Mono", 1, 48)); // NOI18N
        iniciarSes.setText("Iniciar Sesión");
        background.add(iniciarSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 460, 50));

        fieldUsuario.setFont(new java.awt.Font("Lato Semibold", 0, 12)); // NOI18N
        fieldUsuario.setForeground(new java.awt.Color(204, 204, 204));
        fieldUsuario.setText("Ingrese su nombre de usuario");
        fieldUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldUsuarioMouseClicked(evt);
            }
        });
        fieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsuarioActionPerformed(evt);
            }
        });
        background.add(fieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 390, 50));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        iniciarSes1.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        iniciarSes1.setText("Contraseña");
        background.add(iniciarSes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 460, 50));

        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        jLabel1.setText("BookFlow 2025 TM.");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 250, 30));

        fieldContraseña.setForeground(new java.awt.Color(204, 204, 204));
        fieldContraseña.setText("jPasswordField1");
        fieldContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldContraseñaMouseClicked(evt);
            }
        });
        fieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContraseñaActionPerformed(evt);
            }
        });
        background.add(fieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 390, 50));

        accederBtt.setBackground(new java.awt.Color(204, 204, 204));
        accederBtt.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        accederBtt.setText("Acceder");
        accederBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederBttActionPerformed(evt);
            }
        });
        background.add(accederBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 150, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsuarioActionPerformed

    private void fieldUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldUsuarioMouseClicked
        // TODO add your handling code here:
        fieldUsuario.setText("");
    }//GEN-LAST:event_fieldUsuarioMouseClicked

    private void fieldContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldContraseñaMouseClicked
        // TODO add your handling code here:
        fieldContraseña.setText("");
    }//GEN-LAST:event_fieldContraseñaMouseClicked

    private void fieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldContraseñaActionPerformed

    private void accederBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederBttActionPerformed
        // TODO add your handling code here:
        dashboard dash = new dashboard();
        dash.setVisible(true);
    }//GEN-LAST:event_accederBttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton accederBtt;
    private javax.swing.JPanel background;
    private javax.swing.JPasswordField fieldContraseña;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel fondoLogin;
    private javax.swing.JLabel iniciarSes;
    private javax.swing.JLabel iniciarSes1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tituloLogin;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
