/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.conectDb;
import static view.dashboard.fecha;

/**
 *
 * @author YOJHAN DAVID
 */
public class gestionLibros extends javax.swing.JPanel {

    /**
     * Creates new form prestamos
     */
    public gestionLibros() {
        initComponents();
        
        fechaActual.setText(fecha());
    }
    
    private boolean contieneNumeros(String text) {
        for (char c : text.toCharArray()) {
            if (Character.isDigit(c)) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JPanel();
        fechaActual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreLibroAgg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        autorLibroAgg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        añoLibroAgg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        categoriaLibroAgg = new javax.swing.JTextField();
        eliminarLibroBtt = new javax.swing.JButton();
        aggLibroBtt = new javax.swing.JButton();
        actualizarLibroBtt = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner.setBackground(new java.awt.Color(153, 204, 255));
        banner.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechaActual.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        fechaActual.setText("DD/MM/YYYY");
        banner.add(fechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 100));

        jLabel1.setFont(new java.awt.Font("Lato Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Bienvenido al apartado para agregar, actualizar y eliminar libros de la biblioteca de BookFlow:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 580, 30));

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 2, 14)); // NOI18N
        jLabel2.setText("Ingrese el año de publicación:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 250, 30));
        add(nombreLibroAgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 220, 40));

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 2, 14)); // NOI18N
        jLabel3.setText("Ingrese el nombre del libro:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 230, 30));
        add(autorLibroAgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 220, 40));

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 2, 14)); // NOI18N
        jLabel4.setText("Ingrese el autor del libro:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 230, 30));
        add(añoLibroAgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 220, 40));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 2, 14)); // NOI18N
        jLabel5.setText("Ingrese la categoria:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 230, 30));
        add(categoriaLibroAgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 220, 40));

        eliminarLibroBtt.setBackground(new java.awt.Color(153, 204, 255));
        eliminarLibroBtt.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        eliminarLibroBtt.setText("Eliminar Libro");
        eliminarLibroBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarLibroBttActionPerformed(evt);
            }
        });
        add(eliminarLibroBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 150, 50));

        aggLibroBtt.setBackground(new java.awt.Color(153, 204, 255));
        aggLibroBtt.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        aggLibroBtt.setText("Agregar Libro");
        aggLibroBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggLibroBttActionPerformed(evt);
            }
        });
        add(aggLibroBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 140, 50));

        actualizarLibroBtt.setBackground(new java.awt.Color(153, 204, 255));
        actualizarLibroBtt.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        actualizarLibroBtt.setText("Actualizar Libro");
        actualizarLibroBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarLibroBttActionPerformed(evt);
            }
        });
        add(actualizarLibroBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void aggLibroBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggLibroBttActionPerformed
        // TODO add your handling code here:
        
        String nombreLibro = nombreLibroAgg.getText();
        String autorLibro = autorLibroAgg.getText();
        String categoriaLibro = categoriaLibroAgg.getText();
        String año = añoLibroAgg.getText();
        
        int añoLibro = 0;
        
        if(nombreLibro.isEmpty() || autorLibro.isEmpty() || categoriaLibro.isEmpty() || año.isEmpty()) {
                    JOptionPane.showMessageDialog(this, 
                    "Por favor, complete todos los campos.", 
                    "Campos incompletos", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (contieneNumeros(nombreLibro) || contieneNumeros(autorLibro) || contieneNumeros(categoriaLibro)) {
            JOptionPane.showMessageDialog(this,
                    "Los campos Título, Autor y Categoría no deben contener números.",
                    "Error de Formato",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
           try {
            añoLibro = Integer.parseInt(año);
            if (añoLibro <= 0) {
                 throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                    "El Año de publicación no es un número entero válido.", 
                    "Error de Formato", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean registroExitoso = registrarNuevoLibro(nombreLibro, autorLibro, categoriaLibro, añoLibro);

    if (registroExitoso) {
        JOptionPane.showMessageDialog(this, 
                "El libro '" + nombreLibro + "' fue agregado con éxito.", 
                "Libro Agregado", 
                JOptionPane.INFORMATION_MESSAGE);
        
        //Limpiar los campos después del registro
        nombreLibroAgg.setText("");
        autorLibroAgg.setText("");
        categoriaLibroAgg.setText("");
        añoLibroAgg.setText("");
        
    } else {
        JOptionPane.showMessageDialog(this, 
                "Error al registrar el libro. Revise la consola para detalles.", 
                "Error de Registro", 
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_aggLibroBttActionPerformed

    private void actualizarLibroBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarLibroBttActionPerformed
        // TODO add your handling code here:
        
        String nombreLibro = nombreLibroAgg.getText().trim();
    String autorLibro = autorLibroAgg.getText().trim();
    String categoriaLibro = categoriaLibroAgg.getText().trim();
    String año = añoLibroAgg.getText().trim();
    
    int añoLibro = 0;
    
    // 1. Validar campos (Todos son necesarios para identificar y actualizar)
    if(nombreLibro.isEmpty() || autorLibro.isEmpty() || categoriaLibro.isEmpty() || año.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
                "Para actualizar un libro, debe completar todos los campos.", 
                "Campos incompletos", 
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    
        if (contieneNumeros(nombreLibro) || contieneNumeros(autorLibro) || contieneNumeros(categoriaLibro)) {
            JOptionPane.showMessageDialog(this,
                    "Los campos Título, Autor y Categoría no deben contener números.",
                    "Error de Formato",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        try {
            añoLibro = Integer.parseInt(año);
            if (añoLibro <= 0) { //Asegurar que sea un año positivo
                 throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                    "El Año de publicación no es un número entero válido.", 
                    "Error de Formato", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    
    boolean actualizacionExitosa = actualizarLibroExistente(nombreLibro, autorLibro, categoriaLibro, añoLibro);

    if (actualizacionExitosa) {
        JOptionPane.showMessageDialog(this, 
                "Los datos del libro '" + nombreLibro + "' se actualizaron con éxito.", 
                "Actualización Exitosa", 
                JOptionPane.INFORMATION_MESSAGE);
        
        // Limpiar los campos después de la actualización
        nombreLibroAgg.setText("");
        autorLibroAgg.setText("");
        categoriaLibroAgg.setText("");
        añoLibroAgg.setText("");
        
    } else {
        JOptionPane.showMessageDialog(this, 
                "Error al actualizar el libro. Verifique que el Título exista y que la conexión esté activa.", 
                "Error de Actualización", 
                JOptionPane.ERROR_MESSAGE);
    }
    
    
    }//GEN-LAST:event_actualizarLibroBttActionPerformed

    private void eliminarLibroBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLibroBttActionPerformed
        // TODO add your handling code here:
        
        String nombreLibro = nombreLibroAgg.getText().trim();
    String año = añoLibroAgg.getText().trim();
    
    int añoLibro = 0;

    //Validar campos mínimos (Título y Año son necesarios para eliminar con seguridad)
    if(nombreLibro.isEmpty() || año.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
                "Para eliminar un libro, debe ingresar el Título y el Año de publicación.", 
                "Campos incompletos", 
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    
        if (contieneNumeros(nombreLibro)) {
            JOptionPane.showMessageDialog(this,
                    "El campo de titulo no debe contener números.",
                    "Error de Formato",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        try {
            añoLibro = Integer.parseInt(año);
            if (añoLibro <= 0) {
                 throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                    "El Año de publicación no es un número entero válido.", 
                    "Error de Formato", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

    int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea ELIMINAR el libro '" + nombreLibro + "' del catálogo? Esta acción es irreversible.", 
            "Confirmar Eliminación", 
            JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        boolean eliminacionExitosa = eliminarLibroExistente(nombreLibro, añoLibro);

        if (eliminacionExitosa) {
            JOptionPane.showMessageDialog(this, 
                    "El libro '" + nombreLibro + "' fue eliminado con éxito.", 
                    "Eliminación Exitosa", 
                    JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiar los campos
            nombreLibroAgg.setText("");
            autorLibroAgg.setText("");
            categoriaLibroAgg.setText("");
            añoLibroAgg.setText("");
            
        } else {
            JOptionPane.showMessageDialog(this, 
                    "Error al eliminar el libro. Verifique que el Título y Año sean correctos y que el libro exista.", 
                    "Error de Eliminación", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }
        
        
    }//GEN-LAST:event_eliminarLibroBttActionPerformed
    
    //METODO PARA ELIMINAR UN LIBRO EN LA TABLA 
    
    private boolean eliminarLibroExistente(String nombreLibro, int añoLibro) {
    String sqlDelete = "DELETE FROM librosdispo WHERE titulo = ? AND año_publicacion = ?";

    try (Connection connection = new conectDb().conectar();
        PreparedStatement pstDelete = connection.prepareStatement(sqlDelete)) {
        
        pstDelete.setString(1, nombreLibro);
        pstDelete.setInt(2, añoLibro);
        
        int filasAfectadas = pstDelete.executeUpdate();
        return filasAfectadas > 0;

    } catch (SQLException e) {
        System.err.println("Error al eliminar libro: " + e.getMessage());
        return false;
    }
}
    
    
        private boolean registrarNuevoLibro(String nombreLibro, String autorLibro, String categoriaLibro, int añoLibro) {
        Connection cn = null;
        
        String sqlAgregar = "INSERT INTO librosdispo (titulo, autor, categoria, año_publicacion) VALUES (?, ?, ?, ?)";

        try {
            cn = new conectDb().conectar();
            cn.setAutoCommit(false);

            try (PreparedStatement pstAgregar = cn.prepareStatement(sqlAgregar)) {
                pstAgregar.setString(1, nombreLibro);
                pstAgregar.setString(2, autorLibro);
                pstAgregar.setString(3, categoriaLibro);
                pstAgregar.setInt(4, añoLibro);
                
                
                if (pstAgregar.executeUpdate() == 0) {
                    throw new SQLException("Fallo al insertar el registro de préstamo.");
                }
            }
            
            cn.commit();
            return true;

        } catch (SQLException e) {
            if (cn != null) {
                try {
                    cn.rollback();
                } catch (SQLException ex) {
                    System.err.println("Error: " + ex.getMessage());
                }
            }
            System.err.println("Error en transacción de préstamo: " + e.getMessage());
            return false;
            
        } finally {
            if (cn != null) {
                try {
                    cn.setAutoCommit(true);
                    cn.close();
                } catch (SQLException ex) {
                    System.err.println("Error al cerrar recursos: " + ex.getMessage());
                }
            }
        }

    }
        
    private boolean actualizarLibroExistente(String nombreLibro, String autorLibro, String categoriaLibro, int añoLibro) {
    Connection cn = null;
    
    String sqlUpdate = "UPDATE librosdispo SET autor = ?, categoria = ?, año_publicacion = ? WHERE titulo = ?";

    try (Connection connection = new conectDb().conectar();
         PreparedStatement pstUpdate = connection.prepareStatement(sqlUpdate)) {
        
        pstUpdate.setString(1, autorLibro);
        pstUpdate.setString(2, categoriaLibro);
        pstUpdate.setInt(3, añoLibro);
        pstUpdate.setString(4, nombreLibro);
        
        int filasAfectadas = pstUpdate.executeUpdate();
        
        // Retorna true si se actualizó 1 o más filas (es decir, el libro existía)
        return filasAfectadas > 0;

    } catch (SQLException e) {
        System.err.println("Error al actualizar libro: " + e.getMessage());
        return false;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarLibroBtt;
    private javax.swing.JButton aggLibroBtt;
    private javax.swing.JTextField autorLibroAgg;
    private javax.swing.JTextField añoLibroAgg;
    private javax.swing.JPanel banner;
    private javax.swing.JTextField categoriaLibroAgg;
    private javax.swing.JButton eliminarLibroBtt;
    private javax.swing.JLabel fechaActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreLibroAgg;
    // End of variables declaration//GEN-END:variables
}
