/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import model.conectDb;
import static view.dashboard.fecha;


/**
 *
 * @author YOJHAN DAVID
 */
public class historialPrestamos extends javax.swing.JPanel {

    /**
     * Creates new form historialPrestamos
     */
    public historialPrestamos() {
        initComponents();
        cargarTablaPrestamos();
        
        fechaActual.setText(fecha());
    }
    
        private void cargarTablaPrestamos() {
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("ID Prestamo");
    modelo.addColumn("Título");
    modelo.addColumn("ID Usuario");
    modelo.addColumn("Fecha prestamo");

    prestamos_tb.setModel(modelo);

    String sql = "SELECT id_prestamo, titulo, id_usuario, fecha_prestamo FROM prestamos";

    try (Connection cn = new conectDb().conectar();
         PreparedStatement pst = cn.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("id_prestamo"),
                rs.getString("titulo"),
                rs.getInt("id_usuario"),
                rs.getInt("fecha_prestamo")
            });
        }

    } catch (Exception e) {
        System.out.println("Error al cargar libros: " + e);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JPanel();
        fechaActual = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prestamos_tb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner.setBackground(new java.awt.Color(153, 204, 255));
        banner.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechaActual.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        fechaActual.setText("DD/MM/YYYY");
        banner.add(fechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 100));

        jLabel2.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel2.setText("Presentamos el historial de los ultimos prestamos realizados:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        prestamos_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(prestamos_tb);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 148, 368, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pedir-prestado.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banner;
    private javax.swing.JLabel fechaActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable prestamos_tb;
    // End of variables declaration//GEN-END:variables
}
