/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

/**
 *
 * @author YOJHAN DAVID
 */
public class reportes extends javax.swing.JPanel {

    /**
     * Creates new form prestamos
     */
    public reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JPanel();
        fechaActual = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner.setBackground(new java.awt.Color(153, 204, 255));
        banner.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechaActual.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        fechaActual.setText("DD/MM/YYYY");
        banner.add(fechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banner;
    private javax.swing.JLabel fechaActual;
    // End of variables declaration//GEN-END:variables
}
